/* $PSLibId: Run-time Library Release 4.4$ */
#ifndef _HAND1_H_
#define _HAND1_H_

/*****************************************************************
 *
 * file: hand1.h
 *
 * 	Copyright (C) 1994 by Sony Computer Entertainment Inc.
 *				          All Rights Reserved.
 *
 *	Sony Computer Entertainment Inc. Development Department
 *
 *****************************************************************/

u_long hand1[] = {
	0x00000010,
	0x00000008,
	0x0000002c,
	0x01e00000,
	0x00010010,
	0x7fff0000,
	0x03e07c00,
	0x31b52973,
	0x5b1d469c,
	0x7bdf6f7f,
	0x03c07800,
	0x001e7bc0,
	0x03ff781e,
	0x0000008c,
	0x00000280,
	0x00100004,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0x9fffffff,
	0xffffffff,
	0x89ffffff,
	0xffffff56,
	0x778fffff,
	0xffffff56,
	0x7579ffff,
	0xffffff56,
	0x56778fff,
	0xffff7886,
	0x767578ff,
	0xfff67779,
	0x565678ff,
	0xff576676,
	0x65677fff,
	0xff577556,
	0x76566fff,
	0xff567777,
	0x7777ffff,
	0xfff56677,
	0x7776ffff,
	0xffff5566,
	0x777fffff,
	0xfffff566,
	0x777fffff,
	0xfffff566,
};

#endif /* _HAND1_H_ */
/* DON'T ADD STUFF AFTER THIS */

