/* $PSLibId: Run-time Library Release 4.4$ */
#ifndef _HAND2_H_
#define _HAND2_H_

/*****************************************************************
 *
 * file: hand2.h
 *
 * 	Copyright (C) 1994 by Sony Computer Entertainment Inc.
 *				          All Rights Reserved.
 *
 *	Sony Computer Entertainment Inc. Development Department
 *
 *****************************************************************/

u_long hand2[] = {
	0x00000010,
	0x00000008,
	0x0000002c,
	0x01e00000,
	0x00010010,
	0x7fff0000,
	0x03e07c00,
	0x31b52973,
	0x5b1d469c,
	0x7bdf6f7f,
	0x03c07800,
	0x001e7bc0,
	0x03ff781e,
	0x0000008c,
	0x00000280,
	0x00100004,
	0xff68ffff,
	0xffff68ff,
	0xff67ffff,
	0xffff57ff,
	0xff77ffff,
	0xfffff67f,
	0xf67fffff,
	0xfffff67f,
	0xf67fffff,
	0xfffff57f,
	0xf67fffff,
	0xfffff576,
	0x6779ffff,
	0xffffff57,
	0x67578fff,
	0xffffff57,
	0x757879ff,
	0xfff77889,
	0x756777ff,
	0xff576776,
	0x775677ff,
	0xff577557,
	0x77756fff,
	0xff567777,
	0x7777ffff,
	0xfff56677,
	0x7776ffff,
	0xffff5566,
	0x777fffff,
	0xffffff56,
	0x777fffff,
	0xffffff56,
};

#endif /* _HAND2_H_ */
/* DON'T ADD STUFF AFTER THIS */
