LIBDIR   = /usr/psx/lib
INCDIR   = /usr/psx/include
TADDR	 = 80020000	
CC       = cc -EL -G 0 -O2 -I$(INCDIR) 
LIBS     = -lcd -lpress -lgte -lgpu -letc -lc -lapi

all : main	
main.o : menu.h	
OBJS     = main.o balls.o diffuse.o rgb24.o mat.o morph.o mattex.o glasstex.o
main : $(OBJS) 
	ld -L$(LIBDIR) -EL -N -T $(TADDR) -e main -o main $(OBJS) $(LIBS)


