/* $PSLibId: Run-time Library Release 4.4$ */
#ifndef _LIBPS_H_
#define _LIBPS_H_

/*****************************************************************
 *
 * file: libps.h
 *
 * 	Copyright (C) 1994 by Sony Computer Entertainment Inc.
 *				          All Rights Reserved.
 *
 *	Sony Computer Entertainment Inc. Development Department
 *
 *****************************************************************/

#include <sys/types.h>
#include <asm.h>
#include <r3000.h>
#include <libapi.h>
#include <libetc.h>
#include <libgte.h>
#include <libgpu.h>
#include <libgs.h>

extern int MESH_PATTERN;
extern int JAPAN_R;

#endif /* _LIBPS_H_ */
/* DON'T ADD STUFF AFTER THIS */
