/* $PSLibId: Run-time Library Release 4.4$ */
#ifndef _MAXCONF_H_
#define _MAXCONF_H_

/*****************************************************************
 *
 * file: maxconf.h
 *
 * 	Copyright (C) 1994,1995 by Sony Computer Entertainment Inc.
 *				          All Rights Reserved.
 *
 *	Sony Computer Entertainment Inc. Development Department
 *
 *****************************************************************/

#define WAITVSYNC VSync(0)    /* wait vsync before ResetGrpah(3) */

#define COW                   /* Cow Button Pattern */
#define OVAL                  /* Oval Backgoud Pattern */

/* #define EMOUSE                /* Enable Mouse Controle */

/* for JAPAN */
/*#define JAPAN                 /* set Japan area mode for icon moving */
/*#define NOMOUSE               /* Without Mouse Controle */

/* for U/C */
#define ENGLISH               /* English Text for U/C */

#endif /* _MAXCONF_H_ */
/* DON'T ADD STUFF AFTER THIS */
